#!/bin/bash

texFile=$(find . -type f -name "*.tex" -print -quit)

# Check if a .tex file was found
if ! [ -n "$texFile" ]; then
    echo "No .tex files found in this directory or its subdirectories."
    exit 1
fi

xelatex $texFile
